config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :sessions do
    member do
      post 'add_student'
      delete 'remove_student'
    end
  end
  resources :attendances
  resources :search
  root 'landing_page#index'
  resources :landing_page
  get '/import_students/import' => 'import_students#import_page', :as => :csv_import_page
  post '/import_students/imported' => 'import_students#import', :as => :csv_imported
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :session
  belongs_to :student
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/session.rb
class Session < ActiveRecord::Base
  has_many :attendances, dependent: :destroy
  has_many :students, through: :attendances
  def student_list
    students.join(", ")
  end
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |session|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :attendances, dependent: :destroy
  has_many :sessions, through: :attendances
  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/import_students_controller.rb
class ImportStudentsController < ApplicationController
  include CsvImport
  def import
   # initialize
   file = params[:csv_upload] # the file object
   if file
     overwrite = (params[:overwrite] == '1') # update existing users?
     filepath = file.tempfile.path # the rails CSV class needs a filepath

     imported_students = csv_import(filepath)
   end

   # check if input file is valid and return appropriate error message if not
   if valid_input_file?(imported_students, file)
     # create the users and exit
     @hash_of_statuses = import_students(imported_students, overwrite)
     render 'imported'
   end
 end
  
  # functions like the RESTful new action by rendering a form with a GET request
  def import_page
    # limits the options for user.role to the following array, and displays them with more user-friendly labels.
    render 'import' # a form for uploading a csv file of users to import
  end


  private
    # this method checks that the user has uploaded a file and displays flash messages if there is an error.
    # putting these validations in the controller is not idiomatic in rails and there is likely a cleaner way to
    # do this. If we ever have to validate more input than this, we should remove this to a csv_import validations model.
    def valid_input_file?(imported_students, file)
      # check if the user has uploaded a file at all.
      if !file
        flash[:error] = 'Please select a file to upload.'
        redirect_to :back and return
      end



      # make sure the import went with proper headings / column handling
      
      accepted_keys = [:name, :role, :first_name, :nick_name, :goes_by, :last_name, :official_full_name, :net_id, :cell, :yale_email, :yale_email_alias, :non_yale_email, :queue, :old_queue, :college, :class_year, :t_shirt_size, :birthday, :dietary_needs]
      unless imported_students.first.keys == accepted_keys
        flash[:error] = 'Unable to import CSV file. Please ensure that the first line of the file exactly matches the sample input (login, first_name, etc.) Note that headers are case sensitive and must be in the correct order.'
        redirect_to :back and return
      end
      return true
    end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @students = Student.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  include CsvImport
  def index
    @sessions = Session.all
    respond_to do |format|
      format.html
      format.csv { render text: export_sessions(@sessions) }
    end
  end
  def new
    @session = Session.new
  end
  def show
    @session = Session.find(params[:id])
    @attended_students = Session.find(params[:id]).students
    
    respond_to do |format|
      format.html
      format.csv { render text: export_sessions([@session]) }
    end
  end
  def create
    @session = Session.create(session_params)
    redirect_to session_path(@session)
  end
  def destroy
    @session = Session.find(params[:id])
    Session.destroy(@session)
    redirect_to sessions_path
  end
  def add_student
    @session = Session.find(params[:id])
    @attended_students = Session.find(params[:id]).students
    if params[:selected_student]
      student = Student.find(params[:selected_student])
      Attendance.create({:student => student, :session => @session})
      respond_to do |format|
        format.js
      end
    else
      redirect_to sessions_path
    end
  end
  def remove_student
    @session = Session.find(params[:id])
    @attended_students = Session.find(params[:id]).students
    if params[:selected_student]
      student = Student.find(params[:selected_student])
      @session.students.delete(student)
      respond_to do |format|
        format.js
      end
    else
      redirect_to sessions_path
    end
  end
  def update
    redirect_to sessions_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  include StudentsHelper
  def index
    if params[:term]
      session = Session.find(params[:session_id])
      @students = Student.where("name LIKE ? OR nick_name LIKE ? OR net_id LIKE ?", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%")
      @students -= session.students #remove all students that have already attended
    else
      @students = Student.all
    end
    
    respond_to do |format|
      format.html # index.html.erb  
      # Here is where you can specify how to handle the request for "/students.json"
      format.json { render :json => @students.to_json }
    end
  end
  def show
    @student = Student.find(params[:id])
  end
  def new
    @student = Student.new
  end
  def create
    @student = Student.new(student_params)
    @student.save
    redirect_to student_path(@student)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/import_users_helper.rb
module ImportUsersHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def session_params
    params.require(:session).permit(:title, :description, :kind, :date, :selected_student)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
  def student_params
    params.require(:student).permit(:name)
  end

end

app/views/import_students/_import_table.html.erb
<thead>
<tr>
  <th>Login</th>
  <th>Name</th>
  <th>Phone</th>
  <th>Email</th>
  <th>Reason</th>
</tr>
</thead>
<tbody>
  <% students.each do |student_data| %>
    <% student = student_data.first %>
    <tr>
      <td><%= student[:first_name] + ' ' + user[:last_name] %></td>
      <td><%= student[:cell_phone] %></td>
      <td><%= student[:yale_email] %></td>
    </tr>
  <% end %>

app/views/import_students/import.html.erb
<h3>CSV Import Format</h3>
<h5>Columns (must be in the first row of the CSV file)</h5>
<%= form_tag csv_imported_path, :multipart => true do %>

  <p>
    <label>CSV file with users to import:</label>
    <%= file_field_tag 'csv_upload' %>
  </p>
  <p>
    <label>Update existing users' information?</label>
    <%= check_box_tag 'overwrite' %>
  </p>
  <%= submit_tag 'Import Users!', :class => 'btn' %>
<% end %>
<%= link_to "<<Return to Index", landing_page_index_path %>

app/views/import_students/imported.html.erb
<% if @hash_of_statuses %>
  <% unless @hash_of_statuses[:fail].empty? %>
    <h2>students not successfully imported</h2>
    <table class="datatable-wide table table-striped table-bordered" id="student_import_errors_table">
      <%= render :partial => 'import_table', :locals => {:students => @hash_of_statuses[:fail]} %>
    </table>
    <% unless @hash_of_statuses[:success].empty? %>
      <hr />
    <% end %>
  <% end %>

  <% unless @hash_of_statuses[:success].empty? %>
    <h2>Students successfully imported</h2>
      <%= link_to "<<Return to Index", landing_page_index_path %>
      <%= render :partial => 'students/table', :locals => {:students => @hash_of_statuses[:success]} %>
      <%= link_to "Return to Index", landing_page_index_path %>
  <% end %>
<% else %>
  <h2>Please follow <%= link_to "this link", :controller => :import_students, :action => :import_page %> to import students.</h2>
<% end %>

app/views/landing_page/index.html.erb
<h1>
  <%= link_to "Link to Student Directory", students_path %>
</h1>
<h1>
  <%= link_to "Link to Sessions Directory", sessions_path %>
</h1>
<h1>
  <%= link_to "Upload CSV Students", csv_import_page_path %>
</h1>

app/views/layouts/_flash.html.erb
<div id="flashes">
  <%= render 'layouts/flash_alerts' %>
</div>

app/views/layouts/_flash_alerts.html.erb
<%# flash messages, if any %>
  <% flash.each do |name, msg| %>
    <% unless msg.blank? %>
      <%= content_tag :div, :id => "flash_#{name}", :class => "alert alert-#{(name == :notice || name == 'notice') ? "success" : "error"}" do %>
          <button class="close" data-dismiss="alert">×</button>
        <%= msg.gsub(/\n/, "<br />").html_safe %>
      <% end %>
    <% end %>
  <% end %>
  <% flash.clear %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sessions</title>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.min', 'jquery-ui-1.9.2.custom.min.js' %>
  <%= stylesheet_link_tag 'ui-lightness/jquery-ui-1.9.2.custom' %>
  <%= csrf_meta_tags %>
  
</head>
<body>
<%= render 'layouts/flash' %>
<%= yield %>

</body>
</html>

app/views/search/index.html.erb
<h1>Search for a student</h1>
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/students/_info.html.erb
<table id="table_info" class="datatable-wide table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>First Name</th>
    <th>Nickname</th>
    <th>Last Name</th>
    <th>Goes By</th>
    <th>Official Name</th>
    <th>NetID</th>
    <th>Cell Phone</th>
    <th>Yale Email</th>
    <th>Yale Email Alias</th>
    <th>Real Email</th>
    <th>Queue</th>
    <th>Old Queue</th>
    <th>Residential College/Graduate</th>
    <th>Class Year</th>
    <th>Birthday</th>
    <th>Other</th>
  </tr>
    <td><%= link_to @student.name, @student %></td>
    <td><%= link_to @student.first_name, @student %></td>
    <td><%= link_to @student.nick_name, @student %></td>
    <td><%= link_to @student.last_name, @student %></td>
    <td><%= link_to @student.goes_by, @student %></td>
    <td><%= link_to @student.official_full_name, @student %></td>
    <td><%= link_to @student.net_id, @student %></td>
    <td><%= link_to @student.cell, @student %></td>
    <td><%= link_to @student.yale_email, @student %></td>
    <td><%= link_to @student.yale_email_alias, @student %></td>
    <td><%= link_to @student.non_yale_email, @student %></td>
    <td><%= link_to @student.queue, @student %></td>
    <td><%= link_to @student.old_queue, @student %></td>
    <td><%= link_to @student.college, @student %></td>
    <td><%= link_to @student.class_year, @student %></td>
    <td><%= link_to @student.birthday, @student %></td>
    <td><%= link_to @student.other, @student %></td>
  </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/students/_table.html.erb
<table id="table_students" class="datatable-wide table table-striped table-bordered">
  <thead>
  <tr>
    <th>NetID</th>
    <th>First Name</th>
    <th>Nickname</th>
    <th>Last Name</th>
  </tr>
  </thead>
  <tbody>
  <% for student in students %>
    <tr>
    <td><%= link_to student.net_id, student %></td>
    <td><%= link_to student.first_name, student %></td>
    <td><%= link_to student.nick_name, student %></td>
    <td><%= link_to student.last_name, student %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/students/index.html.erb
<h1>All Students</h1>
<%= link_to "<<Return to Index", landing_page_index_path %>
<ul id="students">
  <% @students.each do |student| %>
    <li>
      <%= link_to student.name, student_path(student) %>
    </li>
  <% end %>
  <%= link_to "Create a New Student", new_student_path, class: "new_student" %>
</ul>

app/views/students/new.html.erb
<h1 id = "headline news">Add a new student</h1>
<%= form_for(@student) do |f| %>
  <ul>
  <% @student.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    
  </p>
  <p>
    <%= f.label :birthday %><br />
    <%= f.text_field :birthday %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/students/show.html.erb
<%= link_to "<< Back to Students List", students_path %>
<h1><%= @student.name %></h1>
<%= render :partial => 'info'%>


<h1>Sessions attended</h1>
<ul id="students">
  <% @student.sessions.each do |session| %>
    <li>
      <%= link_to session.title, session_path(session) %>
    </li>
  <% end %>
</ul>